/* Terminal speeds, generated by speeds.sh */
static struct { int s, c; } speeds[] = {
#ifdef B50
	 {       50, B50       },
#endif /* B50 */
#ifdef B75
	 {       75, B75       },
#endif /* B75 */
#ifdef B110
	 {      110, B110      },
#endif /* B110 */
#ifdef B134
	 {      134, B134      },
#endif /* B134 */
#ifdef B150
	 {      150, B150      },
#endif /* B150 */
#ifdef B200
	 {      200, B200      },
#endif /* B200 */
#ifdef B300
	 {      300, B300      },
#endif /* B300 */
#ifdef B600
	 {      600, B600      },
#endif /* B600 */
#ifdef B1200
	 {     1200, B1200     },
#endif /* B1200 */
#ifdef B1800
	 {     1800, B1800     },
#endif /* B1800 */
#ifdef B2400
	 {     2400, B2400     },
#endif /* B2400 */
#ifdef B4800
	 {     4800, B4800     },
#endif /* B4800 */
#ifdef B7200
	 {     7200, B7200     },
#endif /* B7200 */
#ifdef B9600
	 {     9600, B9600     },
#endif /* B9600 */
#ifdef B14400
	 {    14400, B14400    },
#endif /* B14400 */
#ifdef B19200
	 {    19200, B19200    },
#endif /* B19200 */
#ifdef B28800
	 {    28800, B28800    },
#endif /* B28800 */
#ifdef B38400
	 {    38400, B38400    },
#endif /* B38400 */
#ifdef B57600
	 {    57600, B57600    },
#endif /* B57600 */
#ifdef B76800
	 {    76800, B76800    },
#endif /* B76800 */
#ifdef B115200
	 {   115200, B115200   },
#endif /* B115200 */
#ifdef B230400
	 {   230400, B230400   },
#endif /* B230400 */
#ifdef B460800
	 {   460800, B460800   },
#endif /* B460800 */
#ifdef B500000
	 {   500000, B500000   },
#endif /* B500000 */
#ifdef B576000
	 {   576000, B576000   },
#endif /* B576000 */
#ifdef B921600
	 {   921600, B921600   },
#endif /* B921600 */
#ifdef B1000000
	 {  1000000, B1000000  },
#endif /* B1000000 */
#ifdef B1152000
	 {  1152000, B1152000  },
#endif /* B1152000 */
#ifdef B1500000
	 {  1500000, B1500000  },
#endif /* B1500000 */
#ifdef B2000000
	 {  2000000, B2000000  },
#endif /* B2000000 */
#ifdef B2500000
	 {  2500000, B2500000  },
#endif /* B2500000 */
#ifdef B3000000
	 {  3000000, B3000000  },
#endif /* B3000000 */
#ifdef B3500000
	 {  3500000, B3500000  },
#endif /* B3500000 */
#ifdef B4000000
	 {  4000000, B4000000  },
#endif /* B4000000 */
	 {        0, 0         }};
/* EOF */
